-- +goose Up
-- +goose StatementBegin
create table if not exists launches
(
    id           bigint primary key generated by default as identity,
    launch_type  launch_type              not null,
    name         text                     not null,
    description  text                     not null,
    created_at   timestamp with time zone not null default now(),
    updated_at   timestamp with time zone not null default now(),
    finished_at  timestamp with time zone,
    launch_error text
);

create table if not exists train_metrics
(
    launch_id        bigint primary key references launches (id),
    trained_model_id bigint not null references trained_models (id),
    metric_id        bigint not null references metrics (id),
    value            jsonb  not null
);

create table if not exists predict_results
(
    launch_id         bigint primary key references launches (id),
    trained_model_id  bigint         not null references trained_models (id),
    input_dataset_id  bigint         not null references datasets (id),
    status            dataset_status not null,
    output_dataset_id bigint         not null references datasets (id)
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
drop table if exists launches;

drop table if exists train_metrics;

drop table if exists predict_results;
-- +goose StatementEnd
