-- +goose Up
-- +goose StatementBegin
create table if not exists trained_models
(
    id               bigint primary key generated by default as identity,
    name             text                     not null,
    description      text                     not null,
    base_model_id    bigint                   not null references models (id),
    train_dataset_id bigint                   not null references datasets (id),
    launch_id        bigint references launches (id),
    target_col       text                     not null,
    created_at       timestamp with time zone not null default now(),
    updated_at       timestamp with time zone not null default now()
);

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
drop table if exists trained_models;
-- +goose StatementEnd
