// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (int64, error)
	GetUserByExternalID(ctx context.Context, googleID string) (User, error)
	GetUserRolesByEmail(ctx context.Context, email string) ([]string, error)
	GetUserRolesByID(ctx context.Context, id int64) ([]string, error)
}

var _ Querier = (*Queries)(nil)
