version: "3.8"

name: auth

services:
  auth:
    build:
      context: ../../
      dockerfile: build/Dockerfile
    depends_on:
      - db-migrator
    environment:
      - DOTENV_FILE=configs/dev/.env
      - DB_CONNECT_STRING=postgresql://hseuser:P@ssw0rd@db:5432/hsedb
    ports:
      - "8082:8082"
      - "8083:8083"
    networks:
      - hse-net

  db-migrator:
    build:
      context: ../../
      dockerfile: build/migrate/Dockerfile
    command: ["postgresql://hseuser:P@ssw0rd@db:5432/hsedb", "up"]
    depends_on:
      - db
    networks:
      - hse-net

  db:
   image: postgres:16
   restart: always
   environment:
     - POSTGRES_DB=hsedb
     - POSTGRES_USER=hseuser
     - POSTGRES_PASSWORD=P@ssw0rd
     - PGDATA=/var/lib/postgresql/data/pgdata
   ports:
     - '6432:5432'
   volumes:
     - db-data:/var/lib/postgresql/data
   healthcheck:
     test: [ "CMD-SHELL", "pg_isready -U hseuser -d hsedb" ]
     interval: 10s
     timeout: 5s
     retries: 5
     start_period: 10s
   networks:
     - hse-net

volumes:
  db-data:
    driver: local

networks:
  hse-net:
    driver: bridge